config/routes.rb
Rails.application.routes.draw do
  root 'temporary#index'

  get 'login',              to: 'account#login'
  get 'authorize',          to: 'account#authorize'
  put 'update_activities',  to: 'temporary#update_activities'
  put 'update_stats',       to: 'temporary#update_stats'
  get 'leaderboards',       to: 'temporary#calculate_friends_totals'
  get 'leaderboards2',      to: 'temporary#calculate_followers_totals'
end

app/models/activity.rb
class Activity < OpenStruct
  def average_speed_converted
    (self.average_speed / 1000) * 3600
  end

  def self.all athlete_id=nil
    @all ||= Redis.new.keys("activity-#{athlete_id}-*").map do |key|
      self.new.extend(ActivityRepresenter).from_json(Redis.new.get(key))
    end.compact
  end
end

app/models/athlete.rb
class Athlete < OpenStruct
  attr_accessor :athlete_json

  def self.all
    @all ||= Redis.new.keys("athlete-*").map do |key|
      self.new.extend(AthleteRepresenter).from_json(parse_json(Redis.new.get(key)).to_json)
    end.compact
  end

  def self.find_or_create athlete_json
    @athlete_json = athlete_json

    athlete = self.new.extend(AthleteRepresenter).from_json(parse_json(@athlete_json).to_json)

    create_or_update(athlete_json)

    athlete
  end

  def self.find id
    self.new.extend(AthleteRepresenter).from_json(parse_json(read(id)).to_json)
  end

  def access_token
    JSON.parse(Redis.new.get("athlete-#{self.id}"))["access_token"]
  end

  def activities
    Activity.all(self.id)
  end

  def friends
    Friend.all(self.id)
  end

  def followers
    Follower.all(self.id)
  end

  private
  def self.read id
    Redis.new.get("athlete-#{id}")
  end

  def self.create_or_update athlete_json
    Redis.new.set("athlete-#{parse_json(athlete_json)['id']}", athlete_json)
  end

  def self.parse_json athlete_json
    JSON.parse(athlete_json)["athlete"]
  end
end

app/models/follower.rb
class Follower < OpenStruct
  def self.all athlete_id=nil
    @all ||= Redis.new.keys("follower-#{athlete_id}-*").map do |key|
      self.new.extend(AthleteRepresenter).from_json(Redis.new.get(key))
    end.compact
  end

  def stats
    FollowerStat.find(self.id)
  end

  def converted_time
    minutes = convert_time_to_minutes % 60
    hours = convert_time_to_minutes / 60

    format("%03d:%02d:00", hours, minutes) #=> "001:00:00"
  end

  def convert_time_to_minutes
    (convert_read_format.first.to_i * 60) + convert_read_format.last.to_i
  end

  def convert_read_format
    self.stats.year.time.gsub("m", "").split("h ")
  end
end

app/models/follower_stat.rb
class FollowerStat < OpenStruct
  def self.find athlete_id
    self.new.extend(StatRepresenter).from_json(Redis.new.get("stats-#{athlete_id}-follower"))
  end
end

app/models/friend.rb
class Friend < OpenStruct
  def self.all athlete_id=nil
    @all = Redis.new.keys("friend-#{athlete_id}-*").map do |key|
      self.new.extend(AthleteRepresenter).from_json(Redis.new.get(key))
    end.compact
  end

  def stats
    Stat.find(self.id)
  end

  def converted_time
    minutes = convert_time_to_minutes % 60
    hours = convert_time_to_minutes / 60

    format("%03d:%02d:00", hours, minutes) #=> "001:00:00"
  end

  def convert_time_to_minutes
    (convert_read_format.first.to_i * 60) + convert_read_format.last.to_i
  end

  def convert_read_format
    self.stats.year.time.gsub("m", "").split("h ")
  end
end

app/models/map.rb
class Map < OpenStruct
end

app/models/stat.rb
class Stat < OpenStruct
  def self.find athlete_id
    self.new.extend(StatRepresenter).from_json(Redis.new.get("stats-#{athlete_id}"))
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def login
  end

  def authorize
    user = Authentication.new(params).authenticate
    if user.present?
      session[:user_id] = user.id
      redirect_to root_url
    else
      render text: "Unable to authenticate with Strava."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_login
    unless authenticated?
      redirect_to login_path
    end
  end

  def authenticated?
    current_user.present?
  end

  def current_user
    @current_user = user_from_session
  end

  protected
  def user_from_session
    Athlete.find(user_id) if user_id.present?
  end

  def user_id
    session[:user_id]
  end

  def strava_client
    @strava_client ||= Strava::Api::V3::Client.new(access_token: StravaCollector.config.strava[:token])
  end
end

app/controllers/temporary_controller.rb
class TemporaryController < ApplicationController
  before_filter :require_login

  def index
    @activities = @current_user.activities

    respond_to do |format|
      format.html
    end
  end

  def update_activities
    CollectActivitiesJob.perform_now(@current_user.access_token)

    redirect_to root_url
  end

  def update_stats
    CollectFriendsStats.perform_now(@current_user.access_token)

    redirect_to leaderboards_url
  end

  def calculate_friends_totals
    @friends = @current_user.friends

    respond_to do |format|
      format.html
    end
  end

  def calculate_followers_totals
    @followers = @current_user.followers

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StravaCollector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    '//cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css' %>
  <%= javascript_include_tag '//cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js' %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/temporary/calculate_follower_totals.html.erb
<div>
  <%#=link_to "Process Data", update_stats_url, {method: :put, remote: true} %>

  <table id="dataTable" class="table table-striped table-condensed table-hover table-bordered sortable">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Distance</th>
        <th>Sport</th>
        <th>Time</th>
        <th>Elevation</th>
        <th>Time checked</th>
      </tr>
    </thead>
    <tbody>
      <%@followers.each do |follower|%>
        <%begin%>
          <%if !follower.stats.nil?%>
            <tr>
              <td>
                <a href="<%=StravaCollector.config.strava[:athletes_url] + follower.id.to_s%>">
                  <%=follower.id.to_s%>
                </a>
              </td>
              <td><%=follower.firstname%> <%=follower.lastname%></td>
              <td><%=follower.stats.year.distance.gsub(/,/, '').to_f%></td>
              <td><%=follower.stats.year.sport%></td>
              <td><%=follower.converted_time%></td>
              <td><%=follower.stats.year.elevation.gsub(/,/, '').to_f%></td>
              <td><%=Time.at(follower.stats.last_time_checked.to_i)%></td>
            </tr>
          <%end%>
        <%rescue%>
        <%end%>
      <%end%>
    </tbody>
  </table>
</div>

app/views/temporary/calculate_followers_totals.html.erb
<div>
  <%#=link_to "Process Data", update_stats_url, {method: :put, remote: true} %>

  <table id="dataTable" class="table table-striped table-condensed table-hover table-bordered sortable">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Distance</th>
        <th>Sport</th>
        <th>Time</th>
        <th>Elevation</th>
        <th>Time checked</th>
      </tr>
    </thead>
    <tbody>
      <%@followers.each do |follower|%>
        <%begin%>
          <%if !follower.stats.nil?%>
            <tr>
              <td>
                <a href="<%=StravaCollector.config.strava[:athletes_url] + follower.id.to_s%>">
                  <%=follower.id.to_s%>
                </a>
              </td>
              <td><%=follower.firstname%> <%=follower.lastname%></td>
              <td><%=follower.stats.year.distance.gsub(/,/, '').to_f%></td>
              <td><%=follower.stats.year.sport%></td>
              <td><%=follower.converted_time%></td>
              <td><%=follower.stats.year.elevation.gsub(/,/, '').to_f%></td>
              <td><%=Time.at(follower.stats.last_time_checked.to_i)%></td>
            </tr>
          <%end%>
        <%rescue%>
        <%end%>
      <%end%>
    </tbody>
  </table>
</div>

app/views/temporary/calculate_friends_totals.html.erb
<div>
  <%=link_to "Process Data", update_stats_url, {method: :put, remote: true} %>

  <table id="dataTable" class="table table-striped table-condensed table-hover table-bordered sortable">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Distance</th>
        <th>Sport</th>
        <th>Time</th>
        <th>Elevation</th>
        <th>Time checked</th>
      </tr>
    </thead>
    <tbody>
      <%@friends.each do |friend|%>
        <%begin%>
          <%if !friend.stats.nil?%>
            <tr>
              <td>
                <a href="<%=StravaCollector.config.strava[:athletes_url] + friend.id.to_s%>">
                  <%=friend.id.to_s%>
                </a>
              </td>
              <td><%=friend.firstname%> <%=friend.lastname%></td>
              <td><%=friend.stats.year.distance.gsub(/,/, '').to_f%></td>
              <td><%=friend.stats.year.sport%></td>
              <td><%=friend.converted_time%></td>
              <td><%=friend.stats.year.elevation.gsub(/,/, '').to_f%></td>
              <td><%=Time.at(friend.stats.last_time_checked.to_i)%></td>
            </tr>
          <%end%>
        <%rescue%>
        <%end%>
      <%end%>
    </tbody>
  </table>
</div>

app/views/temporary/index.html.erb
<div>
  <%=link_to "Process Data", update_activities_url, {method: :put, remote: true} %>

  <table id="dataTable" class="table table-striped table-condensed table-hover table-bordered sortable">
    <thead>
      <tr>
        <th>ID</th>
        <th>When</th>
        <th>Distance</th>
        <th>Average Speed</th>
        <th>Elevation</th>
        <th>Name</th>
        <th>Kudos Count</th>
        <th>Athlete Count</th>
      </tr>
    </thead>
    <tbody>
      <%@activities.each do |activity|%>
        <tr>
          <td>
            <a href="<%=StravaCollector.config.strava[:activities_url] + activity.id.to_s%>">
              <%=activity.id.to_s%>
            </a>
          </td>
          <td><%=activity.start_date%></td>
          <td><%=activity.distance%></td>
          <td><%=activity.average_speed_converted%></td>
          <td><%=activity.total_elevation_gain%></td>
          <td><%=activity.name%></td>
          <td><%=activity.kudos_count%></td>
          <td><%=activity.athlete_count%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>